export const languageStrings = {
  en: {
    signIn: "Sign In",
    mainHeading: "Find friends, matches create memories.",
    subHeading: "Starts at today. Cancel at any time.",
    welcomeText:
      "Welcome to Amigo, Create your account and meet your matches and friends.",
    createAccount: "Create Account",
    topHeading: "Amigo Member",
    placeHolder1: "India",
    placeHolder2: "Friends",
    countryOptions: [
      { value: "India", label: "India" },
      { value: "Globe", label: "Globe" },
    ],
    partnerOptions: [
      { value: "Friends", label: "Friends" },
      { value: "Partners", label: "Partners" },
    ],
    blockHeading: "More reason to join Amigo",
    emialHeading:
      "Ready to connect? Enter your email to start making meaningful connections.",
    emaillabel: "Email",
    errorMessageemail: "Please enter a valid email",
    emailbutton: "Get Started",
    resourcesTitle: "Resources",
    moreTitle: "More",
    aboutAmigoTitle: "About Amigo",
    legalTitle: "Legal",
    subscribeTitle: "Subscribe to our newsletter",
    subscribeDescription:
      "Stay updated on new releases and features, guides, and case studies.",
    subscribeButton: "Subscribe",
    copyrightText: "Copyright © 2024 Amigo Inc, All right reserved.",
    BHeading : "Frequently Asked Questions",
  },
  hi: {
    signIn: "साइन इन",
    mainHeading: "दोस्तों, मैचों को खोजें, यादें बनाएं।",
    subHeading: "आज शुरू करें। किसी भी समय रद्द करें।",
    welcomeText:
      "अमिगो में आपका स्वागत है, अपना खाता बनाएं और अपने मैचों और दोस्तों से मिलें।",
    createAccount: "खाता बनाएं",
    topHeading: "Amigo सदस्य",
    placeHolder1: "भारत",
    placeHolder2: "दोस्त",
    countryOptions: [
      { value: "India", label: "भारत" },
      { value: "Globe", label: "ग्लोब" },
    ],
    partnerOptions: [
      { value: "Friends", label: "दोस्त" },
      { value: "Partners", label: "साथी" },
    ],
    blockHeading: "Amigo से जुड़ने का और भी कारण",
    emialHeading:
      "कनेक्ट करने के लिए तैयार हैं? सार्थक संबंध बनाना शुरू करने के लिए अपना ईमेल दर्ज करें।",
    emaillabel: "ईमेल",
    errorMessageemail: "कृपया एक मान्य ईमेल दर्ज करें",
    emailbutton: "शुरू करें",
    resourcesTitle: "संसाधन",
    moreTitle: "अधिक",
    aboutAmigoTitle: "Amigo के बारे में",
    legalTitle: "कानूनी",
    subscribeTitle: "हमारे न्यूज़लेटर की सदस्यता लें",
    subscribeDescription:
      "नए रिलीज़ और सुविधाओं, मार्गदर्शिकाओं, और केस स्टडीज़ पर अपडेट रहें।",
    subscribeButton: "सदस्यता लें",
    copyrightText: "कॉपीराइट © 2024 Amigo Inc, सर्वाधिकार सुरक्षित।",
    BHeading : "अक्सर पूछे जाने वाले प्रश्नों",
  },
  es: {
    signIn: "Sesión",
    mainHeading: "Encuentra amigos, los partidos crean recuerdos.",
    subHeading: "Comienza hoy. Cancelar en cualquier momento.",
    welcomeText:
      "Bienvenido a Amigo, crea tu cuenta y conoce a tus parejas y amigos.",
    createAccount: "Crear una cuenta",
    topHeading: "Amigo Miembro",
    placeHolder1: "India",
    placeHolder2: "Amigos",
    countryOptions: [
      { value: "India", label: "India" },
      { value: "Globe", label: "Globo" },
    ],
    partnerOptions: [
      { value: "Friends", label: "Amigos" },
      { value: "Partners", label: "Parejas" },
    ],
    blockHeading: "Más razones para unirte a Amigo",
    emialHeading:
      "¿Listo para conectarse? Ingrese su correo electrónico conexiones significativas.",
    emaillabel: "Correo electrónico",
    errorMessageemail: "Por introduce un correo electrónico válido",
    emailbutton: "Empezar",
    resourcesTitle: "Recursos",
    moreTitle: "Más",
    aboutAmigoTitle: "Sobre Amigo",
    legalTitle: "Legal",
    subscribeTitle: "Suscríbete a Nuestro Boletín",
    subscribeDescription:
      "Mantente informado sobre lanzamientos y, guías y estudios de caso.",
    subscribeButton: "Suscribirse",
    copyrightText: "Derechos de autor © 2024 Amigo Inc, Todos los derechos.",
    BHeading : "Preguntas frecuentes",

  },
  fr: {
    signIn: "Connecter",
    mainHeading: "Trouvez des amis, les matchs créent des souvenirs.",
    subHeading: "Commence à aujourd'hui. Annulez à tout moment.",
    welcomeText:
      "Bienvenue sur Amigo, créez votre compte et rencontrez vos matchs et amis.",
    createAccount: "Créer un compte",
    topHeading: " Amigo Membre",
    placeHolder1: "Inde",
    placeHolder2: "Amis",
    countryOptions: [
      { value: "India", label: "Inde" },
      { value: "Globe", label: "Globe" },
    ],
    partnerOptions: [
      { value: "Friends", label: "Amis" },
      { value: "Partners", label: "Partenaires" },
    ],
    blockHeading: "Raison de plus pour rejoindre Amigo",
    emialHeading:
      "Prêt à vous connecter ? Entrez votre e-mail commencer à établir liens significatifs.",
    emaillabel: "E-mail",
    errorMessageemail: "Veuillez entrer un email valide",
    emailbutton: "Commencer",
    resourcesTitle: "Ressources",
    moreTitle: "Plus",
    aboutAmigoTitle: "À propos d'Amigo",
    legalTitle: "Légal",
    subscribeTitle: "Abonnez-vous à Notre Newsletter",
    subscribeDescription:
      "Restez informé des nouvelles et fonctionnalités,et des études de cas.",
    subscribeButton: "S'abonner",
    copyrightText: "Droits d'auteur © 2024 Amigo Inc, Tous droits réservés.",
    BHeading : "Foire aux questions",
  },
};

export const languageLinks = {
  en: {
    resourcesLinks: [
      "User Guide",
      "Safety Tips",
      "Success Stories",
      "FAQs",
      "Support",
      "Learn",
      "Blog",
    ],
    moreLinks: [
      "How it Works",
      "Community Guidelines",
      "Events",
      "Partnerships",
      "Careers",
      "Policy",
    ],
    aboutVercelLinks: ["About Us", "Team", "Press", "Contact"],
    legalLinks: ["Privacy Policy", "Cookie Policy"],
  },
  hi: {
    resourcesLinks: [
      "उपयोगकर्ता मार्गदर्शिका",
      "सुरक्षा सुझाव",
      "सफलता की कहानियाँ",
      "अक्सर पूछे जाने वाले प्रश्न",
      "समर्थन",
      "सीखें",
      "ब्लॉग",
    ],
    moreLinks: [
      "यह कैसे काम करता है",
      "समुदाय दिशानिर्देश",
      "इवेंट",
      "भागीदारी",
      "करियर",
      "नीति",
    ],
    aboutVercelLinks: ["हमारे बारे में", "टीम", "प्रेस", "संपर्क करें"],
    legalLinks: ["गोपनीयता नीति", "कुकी नीति"],
  },
  es: {
    resourcesLinks: [
      "Guía usuario",
      "Conse seguridad",
      "Historia éxito",
      "Preguntas",
      "Soporte",
      "Aprender",
      "Blog",
    ],
    moreLinks: [
      "Cómo funciona",
      "Normas comunidad",
      "Eventos",
      "Asociaciones",
      "Carreras",
      "Política",
    ],
    aboutVercelLinks: ["Sobre nosotros", "Equipo", "Prensa", "Contacto"],
    legalLinks: ["Política de privacidad", "Política de cookies"],
  },
  fr: {
    resourcesLinks: [
      "Guide tilisateur",
      "Conseils sécurité",
      "Histoir réussite",
      "FAQ",
      "Assistance",
      "Apprendre",
      "Blog",
    ],
    moreLinks: [
      "Comment ça marche",
      "Lignes communauté",
      "Événements",
      "Partenariats",
      "Carrières",
      "Politique",
    ],
    aboutVercelLinks: ["À propos de nous", "Équipe", "Presse", "Contact"],
    legalLinks: ["Politique de confidentialité", "Politique de cookies"],
  },
};
